version: '2'

services:
  app:
    build: .
    volumes:
        - "./app:/src/app"
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
      image: mysql:5.7
      ports:
        - "3306:3306"
      expose:
        - "3306"
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: database_development
          MYSQL_USER: root
          MYSQL_PASSWORD: 1234
